---
- name: Install php-fpm and deps
  sudo: yes
  with_items: "{{ php_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: present

- name: Copy php.ini configuration
  sudo: yes
  template:
    src: php.ini
    dest: /etc/php5/fpm/php.ini
  notify: restart php-fpm
